Add GHA workflow
theforeman/hammer-cli-foreman-tasks pull request #55
Opened 2024-05-30 07:48 UTC by archanaserver

2024-07-16 12:23 UTC, adamruzicka requested changes
I'd be fine with having the rubocop part of this

2024-07-16 12:23 UTC, adamruzicka commented on .github/workflows/ci_test.yml
> +      command: bundle exec rake test
This is not going to fly as there are not tests and therefore no rake task to run them
https://github.com/theforeman/hammer-cli-foreman-tasks/actions/runs/9956681232/job/27507158707?pr=57#step:5:6

2024-07-16 17:30 UTC, archanaserver commented
> I'd be fine with having the rubocop part of this

This make sense, I just dropped the other part. Thanks @adamruzicka.

2024-07-17 08:38 UTC, adamruzicka approved these changes

2024-07-17 08:38 UTC, merged

2024-07-17 08:38 UTC, adamruzicka commented
Thank you @archanaserver !